# This script plots the data generated by run_DEN.py

# Setup --->
import json
import numpy as np
from plot_function import * 

# <--- Setup

# Read Data --->
# read from json file
datafile = open('solution.txt','r')
data = json.loads( datafile.read() )
datafile.close()

# change json datatype to dictionary
keys = []
for i in range(0, len(data)):
	keys.append(data[i][0])
data_dic = {}
for i in range(0, len(data)):
	temp_dic = {keys[i] : data[i][1] }
	data_dic.update(temp_dic)
# <--- Read Data

# Choose Plot Variables --->
print('Choose variables to plot from\n' + str(keys) )
print('')
print('x-axis:')
ordinate = input()
print('How many variables on the y-axis?')
temp_number = int(input())
coordinates = []
for i in range(0,temp_number):
	print('Variable' + str(i+1))
	coordinates.append(input())

data_plot = [ data_dic[ordinate] ]
keys_plot = [ ordinate ]

for i in keys:
	for j in coordinates:
		if i==j:
			keys_plot.append(i)
			data_plot.append(data_dic[i])	
if len(keys_plot) < temp_number:
	print('Check your spelling.')

# <--- Choose Plot Variables
print('plotting' + str(keys_plot))

# plot 
plot2d( data_plot , keys_plot , 'plot')

print('\nPlotting complete. Please find figure in ' + 'plot.pdf.' )
